version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15

  pre_build:
    commands:
      - echo Running tests
      - make test
      - zip goartifacts.zip go.mod application.go handlers/*

artifacts:
  files:
    - goartifacts.zip
